from __future__ import annotations

"""Strategies for extracting image artifacts from a Docling document."""

import logging
from typing import Any, List, Protocol

from document_etl.models import ImageArtifact, SourceDocument
from document_etl.transforms.extractors.document_value_adapter import DocumentValueAdapter

log = logging.getLogger(__name__)


class ImageStrategy(Protocol):
    """Protocol for one image extraction strategy."""

    def extract(self, document: Any, source: SourceDocument, images: List[ImageArtifact]) -> List[ImageArtifact]:
        """Return the images produced by this strategy."""


class PageImageStrategy:
    """Extract page renderings generated by Docling."""

    def extract(self, document: Any, source: SourceDocument, images: List[ImageArtifact]) -> List[ImageArtifact]:
        extracted: List[ImageArtifact] = []
        for page_no, page in getattr(document, "pages", {}).items():
            page_image = getattr(getattr(page, "image", None), "pil_image", None)
            if page_image is None:
                continue
            extracted.append(
                ImageArtifact(
                    index=len(images) + len(extracted) + 1,
                    kind="page",
                    filename=f"page_{int(page_no):03d}.png",
                    image=page_image,
                    page_no=int(page_no),
                )
            )
        return extracted


class PictureImageStrategy:
    """Extract picture crops from Docling picture elements."""

    def extract(self, document: Any, source: SourceDocument, images: List[ImageArtifact]) -> List[ImageArtifact]:
        from docling_core.types.doc import PictureItem

        extracted: List[ImageArtifact] = []
        if not hasattr(document, "iterate_items"):
            return extracted

        picture_counter = 0
        for element, _level in document.iterate_items():
            if not isinstance(element, PictureItem):
                continue
            picture = element.get_image(document)
            if picture is None:
                continue
            picture_counter += 1
            extracted.append(
                ImageArtifact(
                    index=len(images) + len(extracted) + 1,
                    kind="picture",
                    filename=f"picture_{picture_counter:03d}.png",
                    image=picture,
                    page_no=DocumentValueAdapter.first_page_no(element),
                    self_ref=getattr(element, "self_ref", None),
                    provenance=DocumentValueAdapter.provenance(element),
                )
            )
        return extracted


class SourceImageFallbackStrategy:
    """Fallback strategy for image files that produce no derived Docling images."""

    SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp", ".webp"}

    def extract(self, document: Any, source: SourceDocument, images: List[ImageArtifact]) -> List[ImageArtifact]:
        if images or source.extension not in self.SUPPORTED_EXTENSIONS:
            return []

        source_image = self._load_source_image(source)
        if source_image is None:
            return []

        return [
            ImageArtifact(
                index=1,
                kind="source",
                filename="source_image.png",
                image=source_image,
            )
        ]

    @staticmethod
    def _load_source_image(source: SourceDocument) -> Any:
        """Load the original source image when the document produces no derived images."""
        try:
            from PIL import Image

            return Image.open(source.path).convert("RGB")
        except Exception:
            log.debug("failed to load source image path=%s", source.path, exc_info=True)
            return None


class ImageExtractionStrategy:
    """Composite strategy for building the final image artifact list."""

    def __init__(self) -> None:
        self.strategies: List[ImageStrategy] = [
            PageImageStrategy(),
            PictureImageStrategy(),
            SourceImageFallbackStrategy(),
        ]

    def extract(self, document: Any, source: SourceDocument) -> List[ImageArtifact]:
        """Run all image strategies in order and concatenate their outputs."""
        images: List[ImageArtifact] = []
        for strategy in self.strategies:
            images.extend(strategy.extract(document, source, images))
        return images
